### ISSUE TITLE
Screenshot tool can render system very hard to use by creating hard-to-remove overlay

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/gnome-screenshot#4]
When I launch gnome-screenshot --interactive via my panel (using the inbuilt Launcher applet), and choose the 'select area to grab' option (with a ten-second delay), a occasionally I get bizaare situations of the type pictured below.

![image](https://user-images.githubusercontent.com/9998846/29008309-1536dddc-7b04-11e7-8da3-a47b22c44066.png)

![image](https://user-images.githubusercontent.com/9998846/29008324-4289f2a6-7b04-11e7-8e98-eac24ca28fee.png)

In such situations, removing the overlay and closing the screenshot tool is not easy.

Mint 18.2 Cinnamon x64.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/gnome-screenshot/commit/0f137d211d20d398110a8bab9c78f31e5393529f
